### ISSUE TITLE
error: Can't download http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz: 404 Not Found

### ISSUE THREAD

**Issue by crokobit** [chihuahua/beautiful-audio-editor#1]
as title

showing below message after command `sudo easy_install http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz` on osx.

error: Can't download http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz: 404 Not Found

Thanks. 😄

**Comment by chihuahua** [comment]
Thank you for noting that! It seems like the [closure linter is deprecated](https://developers.google.com/closure/utilities/), so we should rely on the `--jscomp_warnings=lintChecks` closure compiler flag.
